#!/usr/bin/env python3

HELP_DICT = {
	'en_us': '''PlaylistExport - Utility for transfering playlists
Usage: [var=/your/path/here ...] /play/list1.m3u /play/list2.m3u ...

Description: Transfer a playlist while maintaining the file hierarchy
found in the music library folder (or from wherever they are being
transfered).

Flags:
-h - display this information and exit
-v - run in verbose mode
-a - autogenerate a playlist from music player settings (gmusicbrowser)
-d - launch prompt to set default settings and exit

Variables:
dst= - destination for copying playlist files to
lib= - path to music library (of the files in destination playlist)
gen_lib= - path to music player library settings (gmusicbrowser only)
gen_dst= - destination for output of autogenerated playlist
r= - rating cutoff, songs < than rating do not get autogenerated

Accepted File Types: .m3u, .m3u8

Note: order of arguments does not matter.'''
}

def display_help(lang='en_us'):
	'''Display the help information'''
	print(HELP_DICT[lang])
